sudo: false

before_install:
     - if [ $TRAVIS_OS_NAME == "linux" ]; then
         sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test;
         sudo apt-get update;
         sudo apt-get install gcc-4.9 g++-4.9;
         sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9;
         export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
         sh -e /etc/init.d/xvfb start;
         sleep 3;

         npm install npm@latest -g;
        fi
install: |
         ./.travis/install.sh

jobs:
  include:
    - script: ./.travis/script.sh
      os: osx
      env: TASK=unit
      language: node_js
      node_js:
      - "lts/*"
    - script: ./.travis/script.sh
      os: linux
      env: TASK=unit
    - script: ./.travis/script.sh
      os: linux
      env: TASK=systestsNode
    - script: ./.travis/script.sh
      os: linux
      env: TASK=systest
    - stage: deploy
      skip_cleanup: true
      provider: script
      script: ./.travis/deploy.sh
      if: branch = master
      if: tag IS present

cache: false
